"""
Multimodal RAG - Step 2: Semantic and Lexical Indexing

This script builds the search databases for our extracted figures.
It uses two search methodologies:
1. Dense Visual Search: We encode the visual image using OpenCLIP (ViT-B-32) 
   and save it into a ChromaDB Vector Store.
2. Sparse Lexical Search: We take the text caption associated with the figure
   and tokenize it into a BM25 index for exact keyword matching.

Dependencies:
    - open_clip_torch
    - chromadb
    - rank_bm25
    - torch
    - Pillow
"""

import os
import json
import torch
import chromadb
import pickle
import open_clip
from PIL import Image
from rank_bm25 import BM25Okapi

# --- Paths Configuration ---
# Where the images and the mapping generated by `extract_images.py` are located
EXTRACTED_DIR = "extracted_data"
IMAGES_DIR = os.path.join(EXTRACTED_DIR, "images")
METADATA_PATH = os.path.join(EXTRACTED_DIR, "images_metadata_d2.json")

# Where we will save our search indices
INDEX_DIR = "index"
os.makedirs(INDEX_DIR, exist_ok=True)


def build_index():
    print(f"Loading metadata map from {METADATA_PATH}")
    if not os.path.exists(METADATA_PATH):
        print("Metadata not found! Please run `extract_images.py` first.")
        return
        
    with open(METADATA_PATH, "r", encoding="utf-8") as f:
        metadata = json.load(f)

    # Use GPU if available, otherwise fallback to CPU
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Loading OpenCLIP ViT-B-32 model on {device}...")
    
    # Initialize the specific vision-language model we are using
    # ViT-B-32 trained on LAION is an excellent semantic baseline
    model, _, preprocess = open_clip.create_model_and_transforms(
        'ViT-B-32', pretrained='laion2b_s34b_b79k'
    )
    model = model.to(device)
    model.eval()

    print("Initializing ChromaDB Store...")
    
    # 1. Setup Persistent ChromaDB Client
    # This stores data locally in the folder, so we don't need a running server
    client = chromadb.PersistentClient(path=os.path.join(INDEX_DIR, "chroma_db"))
    
    # 2. Get or create our specific collection within ChromaDB
    collection = client.get_or_create_collection(
        name="multimodal_figures",
        metadata={"hnsw:space": "cosine"} # Cosine similarity works best for CLIP vectors
    )
    
    # Clear the collection if it already exists to guarantee a fresh, non-duplicated run
    if collection.count() > 0:
        print("Existing collection found. Clearing it and starting completely fresh...")
        client.delete_collection("multimodal_figures")
        collection = client.create_collection(
            name="multimodal_figures",
            metadata={"hnsw:space": "cosine"}
        )

    # BM25 operates on tokenized lists of strings
    tokenized_corpus = []
    
    print("\n--- Starting Embedding Process ---")
    for idx, item in enumerate(metadata):
        # Progress tracker
        if idx % 50 == 0:
            print(f" Processed {idx}/{len(metadata)} items...")
            
        img_path = os.path.join(IMAGES_DIR, item["image_path"])
        if not os.path.exists(img_path):
            continue
            
        try:
            # Step A: Dense Visual Embedding (OpenCLIP)
            # Load the image and process it into the tensor format OpenCLIP expects
            image = Image.open(img_path).convert("RGB")
            image_input = preprocess(image).unsqueeze(0).to(device)
            
            # Run the tensor through the model to get its dense embedding representation
            with torch.no_grad():
                image_features = model.encode_image(image_input)
                # Normalize the features so cosine similarity calculations work properly
                image_features /= image_features.norm(dim=-1, keepdim=True)
                image_features = image_features.cpu().numpy().tolist()[0]
                
            # Insert the newly calculated visual representation into ChromaDB
            # We bundle all the metadata from the JSON along with it
            collection.add(
                ids=[f"fig_{idx}"],
                embeddings=[image_features],
                metadatas=[{
                    "doc_name": item["doc_name"],
                    "image_path": item["image_path"],
                    "context": item.get("context", ""),
                    "page": item.get("page", 0)
                }]
            )
            
            # Step B: Sparse Lexical Indexing (BM25)
            # Get the physical text we found near the figure and tokenize it
            text_context = item.get("context", "")
            tokens = text_context.lower().split()
            tokenized_corpus.append(tokens)
            
        except Exception as e:
            print(f"Error processing {img_path}: {e}")

    # Build the BM25 index on the aggregate list of all caption tokens
    print("\nBuilding BM25 Keyword Search Index...")
    bm25 = BM25Okapi(tokenized_corpus)
    
    # Serialize and save it to disk
    bm25_path = os.path.join(INDEX_DIR, "bm25_index.pkl")
    with open(bm25_path, "wb") as f:
        pickle.dump(bm25, f)
        
    print(f"\nIndexing pipeline complete! Successfully indexed {collection.count()} extracted figures.")


if __name__ == "__main__":
    build_index()
